### PR TITLE
Basic shallow site routes

### LINKED ISSUE #431: Missing generic sites route
Associated Page: https://staging.ecosounds.org/projects/4/edit_sites
Expected Route: `/sites`
Expected Method: `GET`
Expected Body:

- `site[]`

Expected Action:

- Should return a list of all sites
- For logged in users, should return list of all sites they have access to
- For guest users, should return unauthorized

### LINKED ISSUE #437: Failing sites filter route
Route: `https://staging.ecosounds.org/projects/1/sites/filter`

Sites filter route should return filtered list of sites. Currently it returns the following error:

```json
{
    "meta": {
        "status": 404,
        "message": "Not Found",
        "error": {
            "details": "Could not find the requested page.",
            "info": {
                "original_route": "projects/1/sites/filter",
                "original_http_method": "POST"
            }
        }
    },
    "data": null
}
```

### PR DESCRIPTION
**Pull request by Allcharles**
# Index and Filter Shallow Site Routes

Implemented the shallow index and filter routes for the site model.

## Changes

- Modified `index` and `filter` functions in `sites_controller.rb` to support shallow requests
- Created unit tests

## Problems

- Failing tests

## Issues

Closes #437 
Closes #431
Related to #477

### CODE REVIEW

**Comment by Allcharles** [comment]
Currently failing the following tests:

```
rspec ./spec/lib/modules/filter/query_spec.rb:1441 # Filter::Query nested indexes properly filtered restricts sites to project
rspec ./spec/lib/modules/filter/query_spec.rb:1467 # Filter::Query nested indexes properly filtered restricts sites to those in projects that cannot be accessed
rspec ./spec/lib/modules/filter/query_spec.rb:1881 # Filter::Query project with no sites returns no sites for admin
rspec ./spec/lib/modules/filter/query_spec.rb:1898 # Filter::Query project with no sites returns no sites for regular user
```

File: app/controllers/sites_controller.rb [hunk 1]
```diff
@@ -200,9 +204,20 @@ def nav_menu
...
+
+  def get_project_if_exists
+    @project = (Project.find(params[:project_id]) if params.key?(:project_id))
+    # avoid the same project assigned more than once to a site
+    @site.projects << @project if defined?(@site) && defined?(@project) && !@site.projects.include?(@project)
+    @permissions = if @project.nil?
+                     Access::ByPermission.sites(current_user)
+                   else
+                     Access::ByPermission.sites(current_user, project_ids: [@project.id])
+                   end
```
Comment (atruskie) [inline app/controllers/sites_controller.rb:220]: split this out into a different function and don't assign the result to an instance variable - just return it

named something like `list_permissions`

**Comment by Allcharles** [comment]
As discussed on Teams, I'll create a separate PR to change the `ByPermission` functions so they use keyword arguments instead of positional arguments.
