### PR TITLE
Checks that post params is not empty for update and create

### LINKED ISSUE #361: Add better error messages for bad content type headers
Stack trace:

```
NoMethodError (undefined method `[]=' for nil:NilClass):
  app/controllers/dataset_items_controller.rb:94:in `dataset_item_params'
  app/controllers/dataset_items_controller.rb:53:in `create'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:198:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:10:in `process_action'
```

### LINKED ISSUE #366: Bug: NoMethodError occurred in dataset_items#create
A NoMethodError occurred in dataset_items#create:

  undefined method `[]=' for nil:NilClass
  app/controllers/dataset_items_controller.rb:94:in `dataset_item_params'

- URL: https://staging.ecosounds.org/datasets/3/items
- HTTP Method: POST
- Parameters : {"format"=>"json", "controller"=>"dataset_items", "action"=>"create", "dataset_id"=>"3"}

```
-------------------------------
Backtrace:
-------------------------------

  app/controllers/dataset_items_controller.rb:94:in `dataset_item_params'
  app/controllers/dataset_items_controller.rb:53:in `create'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

### PR DESCRIPTION
**Pull request by peichins**
Fixes #366. Fixes #361.

If there are no params, determines whether the request body was empty or if it just was not parsed properly, and responds with approprtiate error code depending on the situation.
If the body was empty, includes an error link to the new action.
If the body was not empty, responds with unsupported_media_type.

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -313,6 +315,37 @@ def store_location(path)
...
 
+  # all create and update actions should have post parameters. If not, in addition to not doing anything,
+  # they might cause errors where these parameters are expected
+  def validate_contains_post_params
+
+    # post values should be in the form {model => {attr => value, attr2 => value}}
+    # an empty body parsed as json will have the form {model => {}}
+    # json body with application/x-www-form-urlencoded content type will have the form {json_string => {}}
+    # json or form encoded with text/plain content type will have the form {}
+    if request.POST.values.all? { |val| val.nil? || (val.is_a?(Hash) && val.empty?) }
```
Comment (atruskie) [inline app/controllers/application_controller.rb]: Simplify this predicate by using `.blank?`

File: app/controllers/application_controller.rb [hunk 2]
```diff
@@ -313,6 +315,37 @@ def store_location(path)
...
+
+      if (request.body.string == "")
```
Comment (atruskie) [inline app/controllers/application_controller.rb]: More idiomatic ruby would use `.blank?` or `.empty?`. Also I believe the parentheses are not needed here

File: app/controllers/application_controller.rb [hunk 3]
```diff
@@ -313,6 +315,37 @@ def store_location(path)
...
+        status = :unsupported_media_type
+        if request.content_type == "text/plain"
+          message = "Request content-type text/plain not supported"
+        else
+          # Catch anything else, but should not reach here because body parsing will have already crashed for
+          # malformed encoding for anything other than text/plain
+          message = "Failed to parse the request body. Ensure that it is formed correctly and matches the content-type (#{request.content_type})"
+        end
+      end
+      render_error(status, message,nil,'validate_contains_params', options)
```
Comment (atruskie) [inline app/controllers/application_controller.rb]: spacing around commas

File: spec/requests/dataset_items_spec.rb [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+  let(:update_dataset_item_attributes) {
+    {end_time_seconds: (dataset_item.end_time_seconds + 5) }
+  }
+
+  before(:each) do
+    @env ||= {}
+    @env['HTTP_AUTHORIZATION'] = admin_token
+
+    @create_dataset_item_url = "/datasets/" + dataset.id.to_s + "/items"
+    @update_dataset_item_url = "/datasets/" + dataset_item.dataset_id.to_s + "/items/" + dataset_item.id.to_s
```
Comment (atruskie) [inline spec/requests/dataset_items_spec.rb]: Can we use `url_helpers` here? Or any rails method for generating the route?
If not, if you use string interpolation (which should do the `.to_s` part for you).

File: spec/requests/dataset_items_spec.rb [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+    end
+
+    # can't catch json content with multipart/form-data content type
+    # because the middleware errors when trying to parse it
+
+    it 'does not allow empty body (nil, json)' do
+      @env['CONTENT_TYPE'] = "application/json"
+      params = nil
+      post @create_dataset_item_url, params, @env
+      expect(response).to have_http_status(400)
```
Comment (atruskie) [inline spec/requests/dataset_items_spec.rb]: should this test have a new resource link as well (like the test below)?

File: spec/requests/dataset_items_spec.rb [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+    end
+
+    it 'allows application/json content-type with json body' do
+      @env['CONTENT_TYPE'] = "application/json"
+      params = {dataset_item: update_dataset_item_attributes}.to_json
+
+      put @update_dataset_item_url, params, @env
+      expect(response).to have_http_status(200)
+    end
+
```
Comment (atruskie) [inline spec/requests/dataset_items_spec.rb]: the update route doesn't get the empty body (400 response) tests?
