### PR TITLE
Decouples spectrogram generation from audio generation

### LINKED ISSUE #527: Partial writes for media cache causing errors
We've been getting a series of errors from the media API, which themselves don't make sense. Looking at the job logs, we get errors like:

-  Invalid data found when processing input
-  WAVE: RIFF header not found
- BawAudioTools::Exceptions::FileEmptyError
- ☝️ those three, repeated, several hundred times

These all happen in the `info_ffmpeg` command, with the target being some bit of cached audio, just before a spectrogram is generated:
```
/home/baw_web/baw-server/lib/gems/baw-audio-tools/lib/baw_audio_tools/run_external_program.rb:63:in `execute'
/home/baw_web/baw-server/lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_base.rb:120:in `info_ffmpeg'
/home/baw_web/baw-server/lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_base.rb:95:in `info'
/home/baw_web/baw-server/lib/gems/baw-audio-tools/lib/baw_audio_tools/spectrogram.rb:50:in `modify'
/home/baw_web/baw-server/lib/gems/baw-workers/lib/baw_workers/media/work_helper.rb:113:in `generate_spectrogram'
/home/baw_web/baw-server/lib/gems/baw-workers/lib/baw_workers/media/action.rb:93:in `make_media_request'
/home/baw_web/baw-server/lib/gems/baw-workers/lib/baw_workers/media/action.rb:25:in `action_perform'
/home/baw_web/baw-server/lib/gems/baw-workers/lib/baw_workers/action_base.rb:110:in `perform'
/home/baw_web/baw-server/lib/gems/resque-status/lib/resque/plugins/status.rb:161:in `safe_perform!'
/home/baw_web/baw-server/lib/gems/resque-status/lib/resque/plugins/status.rb:137:in `perform'
```

It looks to me like some kind of race condition. Another media job has started to cut the audio and not yet finished writing the file. 

I've sampled various cached audio files that were the subject of an error, and they're all fine now. Hence my suspicions.

### PR DESCRIPTION
**Pull request by atruskie**
# Decouples spectrogram generation from audio generation

When generating media a spectrogram first needs to cut out the audio it needs. If there's a audio job running for the same segment at the same time we get race conditions.

## Changes

This change makes the spectrogram generation independent of the audio segment (they don't use the same file). This technically makes the service slower (as cut audio won't be used from the cache as frequently). Although not measured, I'd estimate the time it takes to deal with an exception and send an error notification is far longer though.

So net win in terms of performance and reliability.

Also packages in reliability changes that were found to be needed while testing out these race conditions.

Also adds `no_header` to ffmpeg invocations to significantly remove noise from ffmpeg error messages.

Fixes #527

## Visual Changes

N/A

## Final Checklist

- [x] Assign reviewers if you have permission
- [x] Assign labels if you have permission
- [x] Link issues related to PR
- [x] Remove/Reduce warnings from edited files
- [x] Unit tests have been added for changes
- [ ] Ensure CI build is passing

### CODE REVIEW

File: spec/lib/gems/baw_workers/jobs/media/edge_cases_spec.rb [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+  end
+
+  # https://github.com/QutEcoacoustics/baw-server/issues/527
+  context 'race conditions in interleaved audio & spectrograms jobs targeting the same segment' do
+    # we're running all jobs in the RSpec environment not on the workers for this test
+    pause_all_jobs
+
+    def perform_many_times(path, job, payload)
+      # 100 is a good size for general/CI testing - the test should take about 30 seconds
+      # I've manually tested sizes 200 & 300 too, after about 500 the tools start to timeout on my dev box
```
Comment (Allcharles) [inline spec/lib/gems/baw_workers/jobs/media/edge_cases_spec.rb:60]: A wise man once said that people don't run long test suites. If there is a way, adding some sort of flag to the test command to enable/disable slow tests may be a good option. Especially since testing baw-server can already take an extremely long time. It may be an idea to exclude these kind of long tests, and only have them run on the CI

**Review by Allcharles — APPROVED** [review]
Looks fine, unfortunately I don't understand most of the code so I can't give much additional insight

File: spec/lib/gems/baw_workers/jobs/media/edge_cases_spec.rb (hunk 1 above)
Comment (atruskie) [reply spec/lib/gems/baw_workers/jobs/media/edge_cases_spec.rb:60]: Good idea
