### PR TITLE
Fixes Current.ability

### LINKED ISSUE #553: Unhandled error in AudioRecording model API response
```
App 112 output: 2022-01-13T02:13:04.847 I [112:99600] [["22f89bc0-63b4-419b-9075-42e7004c6c9a"]] (14.6ms) AudioRecordingsController -- Completed #show -- {:controller=>"AudioRecordingsController", :action=>"show", :params=>{"id"=>"352803", "audio_recording"=>{}}, :format=>"JSON", :method=>"GET", :path=>"/audio_recordings/352803", :view_runtime=>0.0, :db_runtime=>2.39, :exception_object=>#<NoMethodError: undefined method `can?' for nil:NilClass>, :status=>500, :allocations=>9960, :status_message=>"Internal Server Error"}
App 112 output: 2022-01-13T02:13:08.222 I [112:99600] [["22f89bc0-63b4-419b-9075-42e7004c6c9a"]] ActionMailer::Base -- Delivered mail 61df8ab0d1512_7018510138339@web-02.mail (3366.3ms)
App 112 output: 2022-01-13T02:13:08.223 F [112:99600 abstract_thread_local_var.rb:43] [["22f89bc0-63b4-419b-9075-42e7004c6c9a"]] Rails -- Exception: NoMethodError: undefined method `can?' for nil:NilClass
App 112 output: /home/baw_web/baw-server/app/models/audio_recording.rb:371:in `block in filter_settings'
App 112 output: /home/baw_web/baw-server/app/modules/api/response.rb:432:in `evaluate_capability'
App 112 output: /home/baw_web/baw-server/app/modules/api/response.rb:309:in `block in add_capabilities!'
App 112 output: /home/baw_web/baw-server/app/modules/api/response.rb:308:in `transform_values'
App 112 output: /home/baw_web/baw-server/app/modules/api/response.rb:308:in `add_capabilities!'
App 112 output: /home/baw_web/baw-server/app/modules/api/controller_helper.rb:83:in `respond_show'
App 112 output: /home/baw_web/baw-server/app/controllers/audio_recordings_controller.rb:27:in `show'
App 112 output: /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
App 112 output: /usr/local/bundle/gems/actionpack-6.1.4.1/lib/abstract_controller/base.rb:228:in `process_action'
App 112 output: /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
App 112 output: /usr/local/bundle/gems/actionpack-6.1.4.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
App 112 output: /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
```

### PR DESCRIPTION
**Pull request by atruskie**
# Fixes Current.ability

I had assumed that current_ability would not be set to a useful value when current_user was nil. Actually though, CanCanCan does provide a useful ability instance even when a user is nil and I should not have not set Current.ability when current_user was nil.

Fixes #553

## Changes

Adds more tests for the current class and also fixes aforementioned bug.

## Problems

N/A

## Visual Changes

N/A

## Final Checklist

- [x] Assign reviewers if you have permission
- [x] Assign labels if you have permission
- [x] Link issues related to PR
- [x] Remove/Reduce warnings from edited files
- [x] Unit tests have been added for changes
- [ ] Ensure CI build is passing

### CODE REVIEW

**Review by yupengKenny — APPROVED** [review]
Anthony walked me through this. 
It is looking good now.

**Review by Allcharles — APPROVED** [review]

File: spec/controllers/application_controller_spec.rb [hunk 1]
```diff
@@ -188,4 +188,68 @@ def invoke(test_value, expected = :unprocessable_entity)
...
+      expect(Current.ability.can?(:original, audio_recording)).to eq true
+
+      expect(response.body).to eq('Ability')
+    end
+
+    it 'sets Current.ability even when a user session is not supplied' do
+      response = get :index_ability
+      expect(Current.ability).to be_an_instance_of(Ability)
+
+      # if you're signed in you cannot download an original recording
```
Comment (atruskie) [inline spec/controllers/application_controller_spec.rb:249]:
```suggestion
      # if you're not signed in you cannot download an original recording
```
