### PR TITLE
Missing tag model details

### LINKED ISSUE #436: Missing tags parameters
Associated Page: https://staging.ecosounds.org/admin/tags
API Route: `/tags`

Expected Body:

- [x] `id`
- [x] `text`
- ~`count` <- Not part of the db model~
- [x] `is_taxanomic`
- [x] `type_of_tag`
- [x] `retired`
- [x] `notes`
- [x] `creator_id`
- [x] `updater_id`
- [x] `created_at`
- [x] `updated_at`

### LINKED ISSUE #464: New tag API route missing notes input
Currently the tags controller fails to properly handle a new tag with attached `notes` value.

To replicate:
`POST` `/tags`

Body:

```JSON
{
	"text": "test tag",
	"isTaxanomic": true,
	"typeOfTag": "common_species",
	"notes": {
		"test": 42,
		"value": "testing"
	}
}
```

On request, the following error is given:

image

### PR DESCRIPTION
**Pull request by Allcharles**
# Tag API Route Update

Minor modifications to the tag model, table, and API.

## Changes

- Updated the tag model to expose the following properties:
  - `notes`
  - `creator_id`
  - `updater_id`
  - `created_at`
  - `updated_at`

  ```JSON
  {
    "id": 1,
    "text": "test tag #1",
    "is_taxanomic": false,
    "type_of_tag": "general",
    "retired": false,
    "notes": null,
    "creator_id": 1,
    "updater_id": null,
    "created_at": "2020-06-22T13:30:37.832+10:00",
    "updated_at": "2020-06-22T13:30:37.832+10:00"
  }
  ```

- Modified tags table to change notes column from type `Text` to `JsonB`. Following migration cases were tested manually:

|          test           |              before            |                      after                      |
|-------------------------|----------------------------------|-------------------------------------------------|
| null                    |                                  |                                                 |
| empty_string            |                                  |                                                 |
| object_containing_array | {"123": [1,2,3]}                 | {"123": [1, 2, 3]}                              |
| number                  | 42                               | {"comment": 42}                                 |
| boolean                 | true                             | {"comment": true}                               |
| single_quotes           | ''                               | {"comment": "''"}                               |
| double_quotes           | ""                               | {"comment": "\"\""}                             |
| empty_object            | {}                               | {}                                              |
| valid_multi_object      | {"test": 42,"value": "bob"}      | {"test": 42, "value": "bob"}                    |
| valid_object            | {"testing": "dataloss"}          | {"testing": "dataloss"}                         |
| array                   | [1,2,3]                          | {"comment": [1, 2, 3]}                          |
| open_brackets           | {{{{                             | {"comment": "{{{{"}                             |
| Australian Reed-Warbler | added via powershell rest import | {"comment": "added via powershell rest import"} |

- Enabled tag creation routes to accept notes input  using the following formats:

|          test           |              input                  |              result                     |
|-------------------------|-------------------------------------|-----------------------------------------|
| null                    | { "notes": null }                   | { "notes": null }                       |
| empty_string            | { "notes": "" }                     | { "notes": { } }                        |
| string                  | { "notes": "invalid" }              | 409!                                    |
| string_object           | "{"notes":{ "testing":"value"}}"    | { "notes": { "testing": "value" } }     |
| valid_object            | { "notes": { "testing": "value" } } | { "notes": { "testing": "value" } }     |
| array                   | { "notes": [ 1, 2, 3 ] }            | 409!                                    |

- Created generic `sanitize_associative_array` function in `src/app/controllers/application_controller.rb`. Handles converting an associative array or scalar input strong parameter, and outputs a jsonb compatible hash
  ```ruby
  params[:tag][:notes] = sanitize_associative_array(params[:tag][:notes], 'notes')
  ```

## Issues

- Have not updated admin tag routes (`app/controllers/admin/tags_controller.rb)
  - Currently the route re-uses a lot of the code from the default tags controller. It could be updated to potentially `implement` the default class, or import the `tag_params`
- Test cases need to be built for the following changes
  - [x] Update tag model unit tests
  - [x] Create tag route unit tests
  - [ ] Create migration unit tests #469

## Closes

Closes #464 
Closes #436 
Related #449 
Related #467

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -608,12 +620,27 @@ def should_check_authorization?
...
     end
-    if response.headers.has_key?(:content_length) && response.headers[:content_length].to_i < 0
+    if response.headers.key?(:content_length) && response.headers[:content_length].to_i.negative?
       raise CustomErrors::BadHeaderError
     end
   end
 
+  def sanitize_notes(json)
+    if json.nil?
+      nil
```
Comment (atruskie) [inline app/controllers/application_controller.rb:633]: i think it would be clearer to use explicit `return` statements here

File: app/controllers/application_controller.rb [hunk 2]
```diff
@@ -608,12 +620,27 @@ def should_check_authorization?
...
+    elsif json.is_a? Hash
+      json
+    elsif json.is_a? String
+      begin
+        JSON.parse(json)
+      rescue JSON::ParserError => _e
+        { 'comment' => json }
+      end
+    else
+      raise CustomErrors::BadRequestError, 'Invalid notes input.'
```
Comment (atruskie) [inline app/controllers/application_controller.rb:643]: make field name customise-able - its not always called notes

File: app/controllers/application_controller.rb [hunk 3]
```diff
@@ -608,12 +620,27 @@ def should_check_authorization?
...
+    end
+  end
```
Comment (atruskie) [inline app/controllers/application_controller.rb:645]: your last input case:

```
notes: [1,2,3] => notes: [1,2,3] [WRONG?]
```

won't pass validation here

File: app/controllers/application_controller.rb [hunk 4]
```diff
@@ -608,12 +620,27 @@ def should_check_authorization?
...
+    if response.headers.key?('Content-Length') && response.headers['Content-Length'].to_i.negative?
       raise CustomErrors::BadHeaderError
     end
-    if response.headers.has_key?(:content_length) && response.headers[:content_length].to_i < 0
+    if response.headers.key?(:content_length) && response.headers[:content_length].to_i.negative?
       raise CustomErrors::BadHeaderError
     end
   end
 
+  def sanitize_notes(json)
```
Comment (atruskie) [inline app/controllers/application_controller.rb:631]: if I'm being real picky, you're only receiving JSON in one of the three cases that are handled below... thus not a great name.

File: app/controllers/application_controller.rb (hunk 1 above)
Comment (Allcharles) [reply app/controllers/application_controller.rb:633]: Rubocop automatically formats out the `return` statements so we would need to update the formater. I can make the change if you want

File: app/controllers/application_controller.rb (hunk 3 above)
Comment (Allcharles) [reply app/controllers/application_controller.rb:642]: Not sure what you mean here. That input case works

Comment (Allcharles) [reply app/controllers/application_controller.rb:642]: (although functionality has now changed so ill resolve this)
